name: Build Docker Container Image
on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ferdaozdemir/oyente
          tags: latest
  
